name: mips64-linux-gnu CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lib{gmp,mpc,mpfr,isl,zstd,debuginfod}-dev zlib1g-dev rsync python3

    - name: run shell script
      run: chmod 755 ./new-build.sh; ./new-build.sh
